[build-system]
requires = ["setuptools>=77", "setuptools_scm>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "conesearch-alchemy"
description = "SQLAlchemy extension for indexed cone searches in astronomical catalogs"
readme = "README.md"
authors = [ { name = "Leo Singer", email = "leo.p.singer@nasa.gov" } ]
license = "BSD-3-clause"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Topic :: Database",
    "Topic :: Scientific/Engineering :: Astronomy"
]
dependencies = [
    "sqlalchemy",
]
requires-python = ">=3.10"
dynamic = ["version"]

[project.urls]
source = "https://github.com/skyportal/conesearch-alchemy"

[dependency-groups]
test = [
    "astropy",
    "numpy",
    "psycopg[binary]",
    "pytest",
    "pytest-benchmark",
    "pytest-cov>=5.0.0",
    "pytest-postgresql>=4.0.0",
    "scipy",
]

[tool.setuptools_scm]
